const CONFIG={clientId:'537537688710-m7b8s8ols1ufbcoj1a0oce57hutsq2u6.apps.googleusercontent.com',scope:'openid https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile',api:'https://cadastro-materiais-api.ventinjadi.workers.dev'};
const state={token:localStorage.getItem('materiais_session')||'',user:null,items:[],editing:null,photoBlob:null,photoName:'',previewUrl:'',photoUrls:new Map()};
const $=id=>document.getElementById(id);
document.addEventListener('DOMContentLoaded',()=>{enhanceUi();bind();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});if(state.token)bootstrap()});

function enhanceUi(){
  document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="custom.css">');
  document.title='Meu Almoxarifado';
  document.querySelector('link[rel="icon"]').href='app-icon.png';
  document.querySelector('.mark').outerHTML='<img class="brand-logo" src="logo-app-sumai-ufba-v2.png" alt="Meu Almoxarifado SUMAI/UFBA">';
  document.querySelector('.brand h1').hidden=true;
  const initialIcon=document.querySelector('#welcome .welcome-icon');if(initialIcon)initialIcon.outerHTML='<img src="app-icon.png" alt="" style="width:78px;height:78px;border-radius:24px">';
  const initialTitle=document.querySelector('#welcome h2');if(initialTitle)initialTitle.textContent='Meu Almoxarifado';
  $('connectBtn').textContent='Entrar';
  $('description').closest('.field').insertAdjacentHTML('beforebegin','<div class="field"><label for="quantity">Quantidade <b>*</b></label><input id="quantity" type="number" inputmode="numeric" min="1" step="1" value="1" required></div>');
  $('description').closest('.field').insertAdjacentHTML('afterend','<div class="field"><label for="location">Local <b>*</b></label><select id="location" required><option value="">Selecione</option><option>Almoxarifado 1</option><option>Almoxarifado 2</option><option>Outro</option></select></div><div id="otherLocationField" class="field" hidden><label for="otherLocation">Qual local? <b>*</b></label><input id="otherLocation" maxlength="160" placeholder="Digite o local"></div><div class="storage-position"><div class="field"><label for="shelfNumber">Número da estante <em>(opcional)</em></label><input id="shelfNumber" maxlength="50" placeholder="Ex.: 03"></div><div class="field"><label for="shelfLevel">Número da prateleira <em>(opcional)</em></label><input id="shelfLevel" maxlength="50" placeholder="Ex.: 02"></div></div>');
  $('newBtn').insertAdjacentHTML('beforebegin','<button id="adminBtn" class="ghost" hidden>Usuários</button>');
  $('adminBtn').insertAdjacentHTML('beforebegin','<button id="exportBtn" class="ghost" hidden>Excel</button>');
  document.body.insertAdjacentHTML('beforeend','<dialog id="adminDialog"><section class="modal"><div class="modalhead"><h2>Solicitações de acesso</h2><button id="closeAdmin" class="close">×</button></div><div id="usersList" class="fields"></div></section></dialog>');
}
function bind(){['connectBtn','welcomeConnect'].forEach(id=>$(id).onclick=connectGoogle);$('newBtn').onclick=()=>openForm();$('adminBtn').onclick=openAdmin;$('exportBtn').onclick=exportExcel;$('closeAdmin').onclick=()=>$('adminDialog').close();$('closeBtn').onclick=$('cancelBtn').onclick=closeForm;$('search').oninput=render;$('filter').onchange=render;$('hasNc').onchange=toggleNc;$('location').onchange=toggleOtherLocation;$('photo').onchange=handlePhoto;$('form').onsubmit=submitForm;$('deleteBtn').onclick=removeCurrent}

function connectGoogle(){if(!window.google?.accounts?.oauth2)return toast('O login Google ainda está carregando.');google.accounts.oauth2.initTokenClient({client_id:CONFIG.clientId,scope:CONFIG.scope,callback:async r=>{if(r.error)return toast('Não foi possível entrar com o Google.');try{const res=await fetch(CONFIG.api+'/session',{method:'POST',headers:{Authorization:'Bearer '+r.access_token}}),data=await res.json();if(!res.ok)throw new Error(data.error||'Não foi possível iniciar a sessão.');state.token=data.token;localStorage.setItem('materiais_session',state.token);await bootstrap()}catch(e){toast(e.message)}}}).requestAccessToken({prompt:''})}
async function api(path,options={}){const res=await fetch(CONFIG.api+path,{...options,headers:{Authorization:'Bearer '+state.token,...(options.headers||{})}});const type=res.headers.get('content-type')||'';if(!res.ok){const data=type.includes('json')?await res.json().catch(()=>({})):{};if(res.status===401){state.token='';localStorage.removeItem('materiais_session');showLogin()}throw new Error(data.error||(res.status===401?'Sua sessão expirou. Entre novamente.':'Não foi possível concluir a operação.'))}return res}
async function bootstrap(){setStatus('Verificando seu acesso…');try{const me=await(await api('/me')).json();state.user=me;if(me.status==='approved'){await loadMaterials();showWorkspace();if(me.email==='ventinjadi@gmail.com')$('adminBtn').hidden=false}else showAccessState(me.status)}catch(e){toast(e.message);showLogin()}}
async function loadMaterials(){const data=await(await api('/materials')).json();state.items=data.materials||[];state.user=data.user||state.user;render()}

function showWorkspace(){const canEdit=state.user.role==='editor';$('welcome').hidden=true;$('workspace').hidden=false;$('connectBtn').hidden=true;$('newBtn').hidden=!canEdit;$('exportBtn').hidden=false;setStatus(`${state.user.name} • ${canEdit?'editor':'somente leitura'}`)}
function showLogin(){$('welcome').hidden=false;$('workspace').hidden=true;$('connectBtn').hidden=false;$('newBtn').hidden=true;$('adminBtn').hidden=true;$('exportBtn').hidden=true;$('welcome').innerHTML='<img src="app-icon.png" alt="" style="width:78px;height:78px;border-radius:24px"><h2>Meu Almoxarifado</h2><p>Entre com sua conta Google para acessar.</p><button id="welcomeConnect" class="primary wide">Entrar com Google</button><small>Os materiais ficam no Drive da administradora.</small>';$('welcomeConnect').onclick=connectGoogle;setStatus('Entre com sua conta Google')}
function showAccessState(status){$('welcome').hidden=false;$('workspace').hidden=true;$('connectBtn').hidden=true;$('newBtn').hidden=true;const pending=status==='pending';$('welcome').innerHTML=`<div class="welcome-icon">${pending?'⌛':'+'}</div><h2>${pending?'Acesso aguardando aprovação':'Solicitar acesso'}</h2><p>${pending?'Sua solicitação foi enviada. Assim que Jadi aprovar, você poderá acessar a lista de materiais.':'Envie uma solicitação para acessar e modificar a lista compartilhada.'}</p>${pending?'':'<button id="requestAccess" class="primary wide">Solicitar acesso</button>'}<small>${esc(state.user.email)}</small>`;if(!pending)$('requestAccess').onclick=requestAccess;setStatus(state.user.name)}
async function requestAccess(){const b=$('requestAccess');b.disabled=true;b.textContent='Enviando…';try{const data=await(await api('/access-request',{method:'POST'})).json();showAccessState(data.status);toast('Solicitação enviada.')}catch(e){toast(e.message);b.disabled=false;b.textContent='Solicitar acesso'}}

async function openAdmin(){try{const data=await(await api('/admin/users')).json();renderUsers(data.users||[]);$('adminDialog').showModal()}catch(e){toast(e.message)}}
function renderUsers(users){$('usersList').innerHTML=users.length?users.map(u=>`<article style="padding:14px;border:1px solid var(--line);border-radius:14px"><strong>${esc(u.name||u.email)}</strong><div style="color:var(--muted);font-size:.84rem;margin:3px 0 10px">${esc(u.email)} • ${labelStatus(u.status,u.role)}</div><div style="display:flex;flex-wrap:wrap;gap:8px"><button class="danger" onclick="decideUser('${esc(u.email)}','rejected','')">Recusar</button><button class="ghost" onclick="decideUser('${esc(u.email)}','approved','viewer')">Somente leitura</button><button class="primary" onclick="decideUser('${esc(u.email)}','approved','editor')">Editor</button></div></article>`).join(''):'<div class="empty">Nenhuma solicitação recebida.</div>'}
async function decideUser(email,status,role){try{await api('/admin/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,status,role})});toast(status==='approved'?(role==='viewer'?'Acesso somente leitura liberado.':'Acesso de editor liberado.'):'Acesso recusado.');await openAdmin()}catch(e){toast(e.message)}}
function labelStatus(s,role){if(s==='approved')return role==='viewer'?'Somente leitura':'Editor';return({pending:'Pendente',rejected:'Recusado'})[s]||s}

function materialLocation(x){return x.location==='Outro'?(x.otherLocation||'Outro'):(x.location||'Local não informado')}
function render(){const q=$('search').value.trim().toLowerCase(),f=$('filter').value;const items=state.items.filter(x=>[x.name,x.description,x.ncNumber,x.responsible,materialLocation(x),x.shelfNumber,x.shelfLevel,x.updatedBy?.name].join(' ').toLowerCase().includes(q)&&(f==='all'||(f==='nc'&&x.hasNc)||(f==='no-nc'&&!x.hasNc))).sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt));$('summary').textContent=items.length===1?'1 material cadastrado':items.length+' materiais cadastrados';$('list').innerHTML=items.length?items.map(card).join(''):'<div class="empty"><strong>Nenhum material encontrado</strong><p>Cadastre um item ou altere a busca.</p></div>';items.forEach(loadCardPhoto)}
function card(x){return `<article class="card" data-id="${esc(x.id)}"><div class="photo">${x.photoId?`<img data-photo="${esc(x.photoId)}" alt="Foto de ${esc(x.name)}">`:'Foto'}</div><div class="content"><h2 class="title">${esc(x.name)}</h2><p class="desc">${esc(x.description)}</p><div class="meta"><span class="chip">Qtd. ${esc(x.quantity||1)}</span><span class="chip location">${esc(materialLocation(x))}</span>${x.shelfNumber?`<span class="chip">Estante ${esc(x.shelfNumber)}</span>`:''}${x.shelfLevel?`<span class="chip">Prateleira ${esc(x.shelfLevel)}</span>`:''}${x.hasNc?`<span class="chip nc">${esc(x.ncNumber)}</span>`:'<span class="chip">Sem NC</span>'}${x.responsible?`<span class="chip">${esc(x.responsible)}</span>`:''}</div><small style="color:var(--muted);margin-top:9px">Alterado por ${esc(x.updatedBy?.name||'—')}</small></div></article>`}
async function loadCardPhoto(x){if(!x.photoId)return;try{const img=document.querySelector(`[data-photo="${CSS.escape(x.photoId)}"]`);if(img)img.src=await getPhotoUrl(x.photoId)}catch{}}
async function getPhotoUrl(id){if(state.photoUrls.has(id))return state.photoUrls.get(id);const blob=await(await api('/photos/'+encodeURIComponent(id))).blob();const url=URL.createObjectURL(blob);state.photoUrls.set(id,url);return url}
document.addEventListener('click',e=>{const c=e.target.closest('.card');if(c&&state.user?.role==='editor')openForm(state.items.find(x=>x.id===c.dataset.id))});

async function openForm(item=null){state.editing=item;state.photoBlob=null;state.photoName='';if(state.previewUrl)URL.revokeObjectURL(state.previewUrl);state.previewUrl='';$('form').reset();$('quantity').value=1;$('formTitle').textContent=item?'Editar material':'Novo material';$('deleteBtn').hidden=!item;$('preview').textContent='Foto';if(item){$('name').value=item.name;$('quantity').value=item.quantity||1;$('description').value=item.description;$('hasNc').checked=item.hasNc;$('ncNumber').value=item.ncNumber||'';$('responsible').value=item.responsible||'';$('location').value=item.location||'';$('otherLocation').value=item.otherLocation||'';$('shelfNumber').value=item.shelfNumber||'';$('shelfLevel').value=item.shelfLevel||'';if(item.photoId)getPhotoUrl(item.photoId).then(url=>$('preview').innerHTML=`<img src="${url}" alt="Foto atual">`)}toggleNc();toggleOtherLocation();$('dialog').showModal()}
function closeForm(){if(!$('saveBtn').disabled)$('dialog').close()}
function toggleNc(){$('ncField').hidden=!$('hasNc').checked;$('ncNumber').required=$('hasNc').checked;if(!$('hasNc').checked)$('ncNumber').value=''}
function toggleOtherLocation(){const other=$('location').value==='Outro';$('otherLocationField').hidden=!other;$('otherLocation').required=other;if(!other)$('otherLocation').value=''}
async function handlePhoto(e){const file=e.target.files[0];if(!file)return;try{toast('Preparando foto…');state.photoBlob=await compressPhoto(file);state.photoName=(file.name||'foto').replace(/\.[^.]+$/,'.jpg');if(state.previewUrl)URL.revokeObjectURL(state.previewUrl);state.previewUrl=URL.createObjectURL(state.photoBlob);$('preview').innerHTML=`<img src="${state.previewUrl}" alt="Prévia">`;toast('Foto pronta.')}catch{state.photoBlob=null;e.target.value='';toast('A foto é grande demais. Reduza a resolução da câmera.')}}
async function compressPhoto(file){if('createImageBitmap'in window){let bitmap;try{bitmap=await createImageBitmap(file,{resizeWidth:1200,resizeQuality:'high'})}catch{bitmap=await createImageBitmap(file)}const scale=Math.min(1,1200/Math.max(bitmap.width,bitmap.height)),w=Math.max(1,Math.round(bitmap.width*scale)),h=Math.max(1,Math.round(bitmap.height*scale)),canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;canvas.getContext('2d',{alpha:false}).drawImage(bitmap,0,0,w,h);bitmap.close();return canvasToBlob(canvas,.78)}return legacyCompress(file,1200,.78)}
function canvasToBlob(canvas,quality){return new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('Falha ao comprimir')),'image/jpeg',quality))}
function legacyCompress(file,max,quality){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),img=new Image();img.onerror=()=>{URL.revokeObjectURL(url);reject()};img.onload=()=>{const scale=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));canvas.getContext('2d',{alpha:false}).drawImage(img,0,0,canvas.width,canvas.height);URL.revokeObjectURL(url);canvasToBlob(canvas,quality).then(resolve,reject)};img.src=url})}
async function submitForm(e){e.preventDefault();if(!state.editing&&!state.photoBlob)return toast('Inclua uma foto do material.');const quantity=Number($('quantity').value);if(!Number.isInteger(quantity)||quantity<1)return toast('Informe uma quantidade válida.');setBusy(true);try{const payload={id:state.editing?.id||'',name:$('name').value.trim(),quantity,description:$('description').value.trim(),hasNc:$('hasNc').checked,ncNumber:$('ncNumber').value.trim(),responsible:$('responsible').value.trim(),location:$('location').value,otherLocation:$('otherLocation').value.trim(),shelfNumber:$('shelfNumber').value.trim(),shelfLevel:$('shelfLevel').value.trim()},form=new FormData();form.append('payload',JSON.stringify(payload));if(state.photoBlob)form.append('photo',state.photoBlob,state.photoName);const data=await(await api('/materials',{method:'POST',body:form})).json(),i=state.items.findIndex(x=>x.id===data.item.id);if(i>=0)state.items[i]=data.item;else state.items.push(data.item);$('dialog').close();render();toast('Material salvo.')}catch(e){toast(e.message)}finally{setBusy(false)}}

async function exportExcel(){if(!state.items.length)return toast('Não há materiais para exportar.');try{await ensureXlsx();const rows=state.items.filter(x=>!x.deletedAt).map(x=>({'Material':x.name,'Quantidade':Number(x.quantity||0),'Descrição':x.description,'Local':materialLocation(x),'Estante':x.shelfNumber||'','Prateleira':x.shelfLevel||'','NC':x.hasNc?(x.ncNumber||'Sim'):'Sem NC','Responsável':x.responsible||'','Cadastrado por':x.createdBy?.name||'','Cadastrado em':formatDate(x.createdAt),'Última alteração por':x.updatedBy?.name||'','Última alteração em':formatDate(x.updatedAt)}));const sheet=XLSX.utils.json_to_sheet(rows);sheet['!cols']=[{wch:24},{wch:12},{wch:42},{wch:24},{wch:12},{wch:14},{wch:18},{wch:24},{wch:24},{wch:20},{wch:24},{wch:20}];sheet['!autofilter']={ref:`A1:L${rows.length+1}`};const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,sheet,'Materiais');XLSX.writeFile(book,`relatorio-materiais-${new Date().toISOString().slice(0,10)}.xlsx`)}catch{toast('Não foi possível gerar o Excel. Verifique a internet.')}}
function ensureXlsx(){if(window.XLSX)return Promise.resolve();return new Promise((resolve,reject)=>{const existing=document.querySelector('script[data-xlsx]');if(existing){existing.addEventListener('load',resolve,{once:true});existing.addEventListener('error',reject,{once:true});return}const script=document.createElement('script');script.src='https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js';script.dataset.xlsx='true';script.onload=resolve;script.onerror=reject;document.head.appendChild(script)})}
function formatDate(value){if(!value)return '';return new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(value))}
async function removeCurrent(){if(!state.editing||!confirm('Excluir este material e sua foto?'))return;setBusy(true);try{await api('/materials/'+encodeURIComponent(state.editing.id),{method:'DELETE'});state.items=state.items.filter(x=>x.id!==state.editing.id);$('dialog').close();render();toast('Material excluído.')}catch(e){toast(e.message)}finally{setBusy(false)}}
function setBusy(on){$('saveBtn').disabled=on;$('deleteBtn').disabled=on;$('saveBtn').textContent=on?'Salvando…':'Salvar'}
function setStatus(s){$('driveStatus').textContent=s}
function toast(msg){const el=$('toast');el.textContent=msg;el.classList.add('show');clearTimeout(el.t);el.t=setTimeout(()=>el.classList.remove('show'),3400)}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
