const CONFIG={clientId:'537537688710-m7b8s8ols1ufbcoj1a0oce57hutsq2u6.apps.googleusercontent.com',scope:'https://www.googleapis.com/auth/drive.appdata',dbName:'materiais-database.json'};
const state={token:'',dbFileId:'',items:[],editing:null,photoBlob:null,photoName:'',previewUrl:'',photoUrls:new Map()};
const $=id=>document.getElementById(id);
document.addEventListener('DOMContentLoaded',()=>{bind();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{})});
function bind(){['connectBtn','welcomeConnect'].forEach(id=>$(id).onclick=connectDrive);$('newBtn').onclick=()=>openForm();$('closeBtn').onclick=$('cancelBtn').onclick=closeForm;$('search').oninput=render;$('filter').onchange=render;$('hasNc').onchange=toggleNc;$('photo').onchange=handlePhoto;$('form').onsubmit=submitForm;$('deleteBtn').onclick=removeCurrent}
function connectDrive(){if(!window.google?.accounts?.oauth2)return toast('A conexÃ£o Google ainda estÃ¡ carregando. Tente novamente.');google.accounts.oauth2.initTokenClient({client_id:CONFIG.clientId,scope:CONFIG.scope,callback:async r=>{if(r.error)return toast('NÃ£o foi possÃ­vel conectar ao Drive.');state.token=r.access_token;await loadDatabase()}}).requestAccessToken({prompt:''})}
async function drive(path,options={}){const res=await fetch('https://www.googleapis.com'+path,{...options,headers:{Authorization:'Bearer '+state.token,...(options.headers||{})}});if(res.status===401){state.token='';showLogin();throw new Error('Sua conexÃ£o expirou. Conecte novamente.')}if(!res.ok){const e=await res.json().catch(()=>({}));throw new Error(e.error?.message||'Erro ao acessar o Google Drive.')}return res}
async function loadDatabase(){setStatus('Abrindo seus materiaisâ€¦');try{const q=encodeURIComponent(`name='${CONFIG.dbName}' and 'appDataFolder' in parents and trashed=false`);const found=await(await drive(`/drive/v3/files?spaces=appDataFolder&q=${q}&fields=files(id,name)&pageSize=1`)).json();if(found.files.length){state.dbFileId=found.files[0].id;const db=await(await drive(`/drive/v3/files/${state.dbFileId}?alt=media`)).json();state.items=Array.isArray(db.items)?db.items:[]}else await writeDatabase();showWorkspace();render()}catch(e){toast(e.message);showLogin()}}
async function writeDatabase(){const data=JSON.stringify({version:1,updatedAt:new Date().toISOString(),items:state.items});if(state.dbFileId){await drive(`/upload/drive/v3/files/${state.dbFileId}?uploadType=media`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:data});return}const meta=JSON.stringify({name:CONFIG.dbName,parents:['appDataFolder']});const created=await multipartUpload(meta,new Blob([data],{type:'application/json'}),'application/json');state.dbFileId=created.id}
async function multipartUpload(meta,blob,mime){const boundary='boundary_'+Date.now();const body=new Blob([`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${meta}\r\n--${boundary}\r\nContent-Type: ${mime}\r\n\r\n`,blob,`\r\n--${boundary}--`],{type:'multipart/related; boundary='+boundary});return(await(await drive('/upload/drive/v3/files?uploadType=multipart&fields=id',{method:'POST',headers:{'Content-Type':'multipart/related; boundary='+boundary},body})).json())}
async function uploadPhoto(blob,name){return(await multipartUpload(JSON.stringify({name:'material-'+Date.now()+'-'+safeName(name||'foto.jpg'),parents:['appDataFolder']}),blob,'image/jpeg')).id}
async function deleteDriveFile(id){if(id)await drive('/drive/v3/files/'+encodeURIComponent(id),{method:'DELETE'}).catch(()=>{})}
async function getPhotoUrl(id){if(!id)return'';if(state.photoUrls.has(id))return state.photoUrls.get(id);const blob=await(await drive(`/drive/v3/files/${id}?alt=media`)).blob();const url=URL.createObjectURL(blob);state.photoUrls.set(id,url);return url}
function showWorkspace(){$('welcome').hidden=true;$('workspace').hidden=false;$('connectBtn').hidden=true;$('newBtn').hidden=false;setStatus('Google Drive conectado')}
function showLogin(){$('welcome').hidden=false;$('workspace').hidden=true;$('connectBtn').hidden=false;$('newBtn').hidden=true;setStatus('Conecte seu Google Drive')}
function setStatus(s){$('driveStatus').textContent=s}
function render(){const q=$('search').value.trim().toLowerCase(),f=$('filter').value;const items=state.items.filter(x=>[x.name,x.description,x.ncNumber,x.responsible].join(' ').toLowerCase().includes(q)&&(f==='all'||(f==='nc'&&x.hasNc)||(f==='no-nc'&&!x.hasNc))).sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt));$('summary').textContent=items.length===1?'1 material cadastrado':items.length+' materiais cadastrados';$('list').innerHTML=items.length?items.map(card).join(''):'<div class="empty"><strong>Nenhum material encontrado</strong><p>Cadastre um item ou altere a busca.</p></div>';items.forEach(async x=>{if(!x.photoId)return;try{const img=document.querySelector(`[data-photo="${CSS.escape(x.photoId)}"]`);if(img)img.src=await getPhotoUrl(x.photoId)}catch{}})}
function card(x){return `<article class="card" data-id="${esc(x.id)}"><div class="photo">${x.photoId?`<img data-photo="${esc(x.photoId)}" alt="Foto de ${esc(x.name)}">`:'Foto'}</div><div class="content"><h2 class="title">${esc(x.name)}</h2><p class="desc">${esc(x.description)}</p><div class="meta">${x.hasNc?`<span class="chip nc">${esc(x.ncNumber)}</span>`:'<span class="chip">Sem NC</span>'}${x.responsible?`<span class="chip">${esc(x.responsible)}</span>`:''}</div></div></article>`}
document.addEventListener('click',e=>{const c=e.target.closest('.card');if(c)openForm(state.items.find(x=>x.id===c.dataset.id))});
async function openForm(item=null){state.editing=item;state.photoBlob=null;state.photoName='';if(state.previewUrl)URL.revokeObjectURL(state.previewUrl);state.previewUrl='';$('form').reset();$('formTitle').textContent=item?'Editar material':'Novo material';$('deleteBtn').hidden=!item;$('preview').textContent='Foto';if(item){$('name').value=item.name;$('description').value=item.description;$('hasNc').checked=item.hasNc;$('ncNumber').value=item.ncNumber||'';$('responsible').value=item.responsible||'';if(item.photoId)getPhotoUrl(item.photoId).then(url=>$('preview').innerHTML=`<img src="${url}" alt="Foto atual">`)}toggleNc();$('dialog').showModal()}
function closeForm(){if(!$('saveBtn').disabled)$('dialog').close()}
function toggleNc(){$('ncField').hidden=!$('hasNc').checked;$('ncNumber').required=$('hasNc').checked;if(!$('hasNc').checked)$('ncNumber').value=''}
async function handlePhoto(e){const file=e.target.files[0];if(!file)return;try{toast('Preparando fotoâ€¦');state.photoBlob=await compressPhoto(file);state.photoName=(file.name||'foto').replace(/\.[^.]+$/,'.jpg');if(state.previewUrl)URL.revokeObjectURL(state.previewUrl);state.previewUrl=URL.createObjectURL(state.photoBlob);$('preview').innerHTML=`<img src="${state.previewUrl}" alt="PrÃ©via">`;toast('Foto pronta.')}catch(err){state.photoBlob=null;e.target.value='';toast('A foto Ã© grande demais para este aparelho. Reduza a resoluÃ§Ã£o da cÃ¢mera e tente novamente.')}}
async function compressPhoto(file){if('createImageBitmap'in window){let bitmap;try{bitmap=await createImageBitmap(file,{resizeWidth:1200,resizeQuality:'high'})}catch{bitmap=await createImageBitmap(file)}const scale=Math.min(1,1200/Math.max(bitmap.width,bitmap.height)),w=Math.max(1,Math.round(bitmap.width*scale)),h=Math.max(1,Math.round(bitmap.height*scale)),canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;canvas.getContext('2d',{alpha:false}).drawImage(bitmap,0,0,w,h);bitmap.close();return canvasToBlob(canvas,.78)}return legacyCompress(file,1200,.78)}
function canvasToBlob(canvas,quality){return new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('Falha ao comprimir')),'image/jpeg',quality))}
function legacyCompress(file,max,quality){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),img=new Image();img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('Falha ao abrir'))};img.onload=()=>{const scale=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));canvas.getContext('2d',{alpha:false}).drawImage(img,0,0,canvas.width,canvas.height);URL.revokeObjectURL(url);canvasToBlob(canvas,quality).then(resolve,reject)};img.src=url})}
async function submitForm(e){e.preventDefault();if(!state.editing&&!state.photoBlob)return toast('Inclua uma foto do material.');setBusy(true);try{let photoId=state.editing?.photoId||'';if(state.photoBlob){const old=photoId;photoId=await uploadPhoto(state.photoBlob,state.photoName);await deleteDriveFile(old)}const now=new Date().toISOString(),item={id:state.editing?.id||crypto.randomUUID(),createdAt:state.editing?.createdAt||now,updatedAt:now,name:$('name').value.trim(),description:$('description').value.trim(),hasNc:$('hasNc').checked,ncNumber:$('hasNc').checked?$('ncNumber').value.trim():'',responsible:$('responsible').value.trim(),photoId};const i=state.items.findIndex(x=>x.id===item.id);if(i>=0)state.items[i]=item;else state.items.push(item);await writeDatabase();$('dialog').close();render();toast('Material salvo no Drive.')}catch(e){toast(e.message)}finally{setBusy(false)}}
async function removeCurrent(){if(!state.editing||!confirm('Excluir este material e sua foto?'))return;setBusy(true);try{await deleteDriveFile(state.editing.photoId);state.items=state.items.filter(x=>x.id!==state.editing.id);await writeDatabase();$('dialog').close();render();toast('Material excluÃ­do.')}catch(e){toast(e.message)}finally{setBusy(false)}}
function setBusy(on){$('saveBtn').disabled=on;$('deleteBtn').disabled=on;$('saveBtn').textContent=on?'Salvandoâ€¦':'Salvar'}
function toast(msg){const el=$('toast');el.textContent=msg;el.classList.add('show');clearTimeout(el.t);el.t=setTimeout(()=>el.classList.remove('show'),3200)}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function safeName(v){return String(v).replace(/[^a-zA-Z0-9._-]/g,'_')}
